Homework_3 done
eugene-okulik/Artew pull request #2
Opened 2024-12-04 13:03 UTC by Mexxonoshin

Отправляю на проверку 4 упражнения из homework_3

2024-12-04 13:17 UTC, Mexxonoshin commented
Евгений, посмотрел checks lint ничего не понял(

2024-12-04 14:26 UTC, eugene-okulik commented
> Евгений, посмотрел checks lint ничего не понял(

А там нечего понимать. Он у тебя не нашел никаких проблем. Но он не нашел ничего потому, что файлы, которые попали в этот пулл реквест - пустые )))

2024-12-04 14:27 UTC, eugene-okulik requested changes
Круто было бы, если бы в файлах было что-то )))

2024-12-04 14:43 UTC, Mexxonoshin commented
Вроде перезалил:)

2024-12-05 06:58 UTC, eugene-okulik requested changes
Отлично, содержимое появилось  
Основная борьба в этом задании не с моей проверкой, а проверкой Lint. И пока что он побеждает )))
Всё хорошо, но нужно исправить все проблемы, которые он нашел.
В видео, которое шло к этому занятию, где-то со времени 1 ч 25 мин я рассказываю как разбираться с проблемами, которые возникают на этом этапе.

2024-12-05 17:54 UTC, eugene-okulik approved these changes
:+1:

2024-12-05 17:54 UTC, merged